[tool.black]
line-length = 88
target-version = ['py310']

[tool.flake8]
max-line-length = 88
exclude = [".git", "__pycache__", "venv", "env", "migrations"]
ignore = ["E203", "W503"]  # E203: whitespace before ':', W503: line break before binary operator